#!/bin/bash

bat=/sys/class/power_supply/BAT0
start=$bat/charge_control_start_threshold
end=$bat/charge_control_end_threshold

if [ ! -f $start ]; then
  echo "Not found: $start"
  return 1
fi

if (( $# )); then
  if (( $1 == 100 )); then
    echo 0 > $start || exit 1
    echo 100 > $end || exit 1
  elif (( $1 >= 0 && $2 >= 1 && $1 < $2 )); then
    echo $1 > $start || exit 1
    echo $2 > $end   || exit 1
  else
    echo "Wrong parameters!"
    return 1
  fi
fi

for i in $bat/*_threshold; do
  echo "`basename $i` = `cat $i`"
done
