#!/bin/bash

ERR=${0##*/}-err.log

shopt -s expand_aliases
alias _parallel="parallel --halt soon,fail=1 --will-cite --colsep=' '"

_mimetype() {
  file --mime-type "$1" | grep -o '\S\+$'
}

_size_bytes() {
  local res
  res=`stat -c %s $1 2>/dev/null`
  if (( $? )); then
    # MacOS
    res=`stat -f %z $1 2>/dev/null`
  fi
  echo $res
}
export -f _size_bytes

_log() {
  printf "$*\n"
}

_usage() {
  local func=${FUNCNAME[1]}
  [[ $func = main ]] && func= || func=" $func"
  printf "Usage: ${0##*/}$func"
}

redhf="\e[91m"
redf="\e[31m"
redb="\e[48;5;52m"
rst="\e[0m"

_param() {
  local out="$rst$redb$redhf $1 $rst"
  shift
  (( $# > 1 )) && out+=" $redf$1$rst" && shift
  out+=" $1"

  _log "$out"
}

ao() {
  if [[ $# != 2 ]]; then
    cat <<EOF
Converts audio-stream only (aac, 2ch, 44.1 kHz, vbr 3)
$(_usage) <input-filename> <output-filename>
EOF
    return 1
  fi

  ffmpeg -i "$1" -hide_banner -c:v copy -c:a libfdk_aac -ac 2 -ar 44100 -vbr 3 "$2"
}

audio() {
  if (( ! $# )); then
    cat <<EOF
Convert tracks from list (libfdk_aac, 2ch, 44.1 kHz)
$(_usage) [--vbr=4|--alow] [-k|--keep] <list>
EOF
    return 1
  fi

  while (( $# )); do
    if [[ "$1" =~ ^--vbr=[1-5]$ ]]; then
      export flags+=" -c:a libfdk_aac -ac 2 -ar 44100 -vbr ${1#*=}"
    elif [[ "$1" = "-alow" ]]; then
      export flags+=" -c:a libfdk_aac -ar 24k -profile:a aac_he_v2 -b:a 8k"
    elif [[ "$1" = "-anorm" ]]; then
	  export flags+=" -af dynaudnorm=f=75:g=25:n=0:p=0.58"
    elif [[ "$1" =~ ^(-k|--keep)$ ]]; then
      export keep=1
    elif [[ "$1" =~ ^- ]]; then
		>&2 echo "Invalid option: $1"
		return 1
    elif [[ $(_mimetype "$1") =~ ^(audio|video) || "$1" = *.m4a ]]; then
      LIST+="\n$1"
    fi
    shift
  done

  if [[ "$flags" != *-c:a* ]]; then
	  export flags+="-c:a libfdk_aac -ac 2 -ar 44100 -vbr 4"
  fi

  export -f _audio_1
  printf "$LIST" | parallel --will-cite _audio_1
  _log "\nDone!"
}

_audio_1() {
  [[ -z $1 ]] && return

  local out="${1%.*}.m4a"
  local out2="${1%.*}-a.m4a"
  ffmpeg -y -i "$1" \
    -hide_banner -v quiet \
    -map 0 -map -0:v \
    $flags \
    "$out2"

  if (( ! $? )) && [[ -f "$out2" ]]; then
    if [[ ! $keep && "$1" != "$out2" ]]; then
      rm "$1"
      mv "$out2" "$out"
    fi
    printf .
  else
    [[ "$1" != "$out2" ]] && rm -f "$out2"
    printf e
  fi
}

photos() {
  if (( ! $# )); then
    cat <<EOF
Convert photos from list (jpeg, 1024x768)
$(_usage) <list>
EOF
    return 1
  fi

  while (( $# )); do
    if [[ $(_mimetype "$1") = image* ]]; then
      [[ -n $LIST ]] && LIST+="\n"
      LIST+="$1"
    fi
    shift
  done

  export -f _photo
  printf "$LIST" | parallel --will-cite _photo
  [[ $? = 0 ]] && _log "\nPhotos were successfully converted." \
               || _log "\nSomething nasty has happened."
}

_photo() {
  # TODO check imagemagick is installed
  local DIM=($(identify -format "%W %H" "$1" 2>/dev/null))
  local W=${DIM[0]:-0}
  local H=${DIM[1]:-0}

  if [[ $? != 0 || ($W -le 1024 && $H -le 1024) ]]; then
    printf _
    return
  fi

  convert "$1" -filter Lanczos -resize 1024x1024 -quality 80 -auto-level "$1"
  [[ $? = 0 ]] && printf . || printf e
}

covers() {
  if (( ! $# )); then
    cat <<EOF
Convert covers from list (jpeg, 900x900 or 600 for wide ones)
$(_usage) [-f] <list>
$(_param -f "creates 500x500 folder.jpg from cover")
EOF
    return 1
  fi

  [[ $1 = -f ]] && F="-f " && shift

  while (( $# )); do
    if [[ $(_mimetype "$1") = image* ]]; then
      [[ -n $LIST ]] && LIST+="\n"
      LIST+="$F$1"
    fi
    shift
  done

  export -f _cover
  printf -- "$LIST" | _parallel _cover
  (( ! $? )) && _log "\nCovers were successfully converted."
}

_cover() {
  Q=80

  [[ $1 = -f ]] && F=1 && shift

  local DIM=($(identify -format "%W %H" "$1" 2>/dev/null))
  [[ $? != 0 ]] && printf e && return 1

  local W=${DIM[0]:-0}
  local H=${DIM[1]:-0}

  local SIZE=$(_size_bytes "$1")
  [[ $? != 0 ]] && printf e && return 1

  if [[ $F = 1 && ${1%.*} = cover ]]; then
    if [[ $W -le 500 && $H -le 500 ]]; then
      cp "$1" folder.jpg
    else
      convert "$1" -filter Lanczos -resize 500x500 -quality $Q folder.jpg
    fi
  fi

  [[ $SIZE -le 131072 || ($W -le 900 && $H -le 900) ]] && printf _ && return

  local R=900x900
  if (( $(bc -l <<< "$W/$H > 1.4") )); then
    R=x600
  elif (( $(bc -l <<< "$H/$W > 1.4") )); then
    R=600
  fi

  convert "$1" -filter Lanczos -resize $R -quality $Q "${1%.*}.jpg"
  [[ $? = 0 ]] && printf . || printf e
}

fix() {
  if (( ! $# )); then
    cat <<EOF
Makes a naive attempt to fix media.
$(_usage) <file> [output]
EOF
    return 1
  fi

  local out=${2-${1%.*}-fixed.${1#*.}}
  ffmpeg -err_detect ignore_err -i $1 -c copy $out
}

videos() {
  if (( ! $# )); then
    cat <<EOF
Converts videos from list (mp4, 2000 kbps, aac vbr 3)
$(_usage) [-ccw] <list>
EOF
    return 1
  fi

  while (( $# )); do
    if [[ "$1" = -ccw ]]; then
      export ccw=1
    elif [[ $(_mimetype "$1") = video* ]]; then
      [[ -n $LIST ]] && LIST+="\n"
      LIST+="$1"
    fi
    shift
  done

  # Two threads per video by default
  #export threads=2
  export -f _video
  printf "$LIST" | parallel --will-cite _video

  echo
  if [[ -s $ERR ]]; then
    _log "Not all videos were converted:"
    cat $ERR
  else
    _log "Videos converted successfully."
  fi

  rm -f $ERR
}

vol() {
	local args=(-filter:a volumedetect -f null /dev/null)
	if [ -n "$2" ]; then
		if [ "$1" = "norm" ]; then
			local target="I=-16:TP=-1.5:LRA=11"
			local measured=$(
				ffmpeg -hide_banner -i "$2" -filter:a loudnorm=$target:print_format=json -f null - 2>&1 \
				| sed -n '/{/,$p' \
				| jq -r '@text "measured_I=\(.input_i):measured_LRA=\(.input_lra):measured_TP=\(.input_tp):measured_thresh=\(.input_thresh):offset=\(.target_offset)"'
			)
			echo $measured
			echo
			args=(-filter:a loudnorm=$target:$measured "${2%.*}-norm.${2##*.}")
		else
			args=(-filter:a volume=$1 "${2%.*}-vol$1.${2##*.}")
		fi
		shift
	fi

	ffmpeg -hide_banner -i "$1" -c:v copy "${args[@]}"
}

_video() {
  local BR_V=$(ffprobe -print_format csv=p=0 -v quiet -show_entries stream=bit_rate -select_streams v "$1")
  if (( $? )); then
    printf e
    _log "BR_V $1" >> "$ERR"
    shift
    return
  fi

  local A=$(ffprobe -print_format csv=p=0 -v quiet -show_entries stream=channels,bit_rate -select_streams a "$1")
  if (( $? )); then
    printf e
    _log "A $1" >> "$ERR"
    shift
    return
  fi

  A=(${A//,/ })
  (( $(bc <<< ${A[1]}/${A[0]}) < 60000 )) && A="-c:a copy" \
                                          || A="-c:a libfdk_aac -ar 44100 -vbr 3"

  (( $BR_V > 2000000 )) && BR_V=2000000

  # local vf="scale=640:trunc(ow/a/2)*2"

  local vf

  [[ ! -z "$ccw" ]] && vf+="${vf:+,}transpose=2"

  local out=`dirname "$1"`"/_"`basename "$1"`

  # TODO use film in parallel and with -passlogfile
  ffmpeg -i "$1" -v quiet -hide_banner -y \
         -map_metadata 0 -movflags use_metadata_tags \
         -c:v libx264 -x264-params threads=${threads:-2} $BV -b:v $BR_V ${vf:+-vf "$vf"}  \
         $A "$out" >/dev/null

  if (( $? )); then
    printf e
    _log "CNV $1" >> "$ERR"
  elif [[ -f "$out" ]]; then
    rm "$1"
    mv "$out" "${1%.*}.mp4"
    printf .
  fi
}

# TODO image + audio
# ffmpeg -y -loop 1 -i image.jpg -i audio.m4a -c:v libx264 -tune stillimage -preset veryslow -crf 51 -r 1 -c:a copy -pix_fmt yuv420p -shortest -movflags +faststart video.mp4
# or: -c:a libfdk_aac -ac 2 -ar 44100 -vbr 4
concat() {
  if (( ! $# )); then
    cat <<EOF
Concats videos from the list.
$(_usage) <videos...> [output.mp4]
EOF
    return 1
  fi
  local files
  local file
  local output
  for f in "$@"; do
    file=$f
    [[ "$file" != /* ]] && file="$PWD/$f"
    if [ -f "$file" ]; then
      files+="file '$file'\n"
    elif [ "$f" = "${@:$#}" ]; then
      output="$f"
    fi
  done
  printf "$files"
  output="${output:=output.mp4}"
  echo "to $output"
  # -c copy \
  ffmpeg -f concat -safe 0 -i <(printf "$files") \
    -c:a libfdk_aac -ar 22050 -profile:a aac_he -vbr 1 -ac 1 \
    $output
}

cut() {
  if (( ! $# )); then
    cat <<EOF
Cuts a media file.
$(_usage) [options] <input.xxx> [03:06|start] [01:05 (dur)|finish] [input-out.yyy]
EOF
    return 1
  fi

  [[ ! "$2" =~ beginning|start ]] && start="-ss $2"
  [[ ! "$3" =~ end|finish ]] && finish="-t $3"

  local ext_in="${1##*.}"
  local out="${4:-${1%.*}-cut.${ext_in}}"
  local ext_out="${out##*.}"

  local is_copy
  [[ "$ext_in" == "$ext_out" ]] && is_copy="-c copy"

  ffmpeg -i "$1" $start $finish $is_copy "$out"
}

film() {
  if (( ! $# )); then
    cat <<EOF
Convert film
$(_usage) [options] <input.xxx> [input-out.xxx]
$(_param "-f|--from" "    00:00:00.000" "Starting time for video encoding")
$(_param "-d|--duration" "00:00:00.000" "Total duration time for video encoding")

$(_param "-b|--bitrate" "000k "  "Video encoding bitrate")
$(_param "-crf" "        17-28" "Video encoding quality (lower is better)")
$(_param "-w|--width" "  000  "  "Output video width (preserves aspect ratio)")
$(_param "-r" "          000  "  "Frame rate")

$(_param "--ultrafast|--superfast|--veryfast|--faster|--fast|--medium|--slow|--slower|--veryslow" "" "Video preset (def: fast)")
$(_param "--film|--animation|--grain|--stillimage|--fastdecode|--zerolatency" "" "Tune")
$(_param "-alow|-ahigh|-an" "" "Audio preset (def: copy)")

$(_param -cw "Rotate 90° clockwise")
$(_param -ccw "Rotate 90° counterclockwise")
$(_param -2 "Perform only 2nd pass encoding")
$(_param -sc "Copy subtitle stream")
$(_param --slow "Use \"slow\" x264 encoding preset (def. \"fast\")")
$(_param "-t|--threads" "auto" "Number of encoding threads")
$(_param --log "quiet|panic|fatal|error|warning|info|verbose|debug|trace" "")

$(_param "-di|--deinterlace")
$(_param "-dn|--denoise" "luma_spatial:chroma_spatial:luma_tmp:chroma_tmp" \
"\nApply denoise filter.
Default values:
luma_spatial   = 4
chroma_spatial = 3
luma_tmp       = 6
chroma_tmp     = 4.5")
$(_param "-ds|--deshake")
$(_param "-anorm|--audio-normalize")

$(_param -eq "contrast:brightness:gamma" \
"\nApply eq flter.
Default values and possible ranges:
contrast   = 1 [-2.0 ..  2.0]
brightness = 0 [-1.0 ..  1.0]
gamma      = 1 [ 0.1 ..  10 ]")

$(_param "-cr|--crop" "width:height:x:y" \
"\nApply crop flter.
x,y - crop start position from top left corner")

$(_param -vf filters "Additional video filters to apply")
EOF
    return 1
  fi

  local preset=fast
  local tune

  local audio="-c:a copy"
  local threads
  local LOG
  local misc=()

  while [[ $# > 1 ]]; do
  case "$1" in
  -f|--from)
    FROM="-ss $2"
    shift ;;
  -d|--duration)
    DUR="-t $2"
    shift ;;
  -b|--bitrate)
    BV="-b:v $2"
    shift ;;
  -crf)
    BV="-crf $2"
	# CRF/CQP is incompatible with 2pass
    p2only=
    shift ;;
  -anorm|--audio-normalize)
    [ -n "$AF" ] && AF+=,
    AF+="dynaudnorm=f=75:g=25:n=0:p=0.58" ;;
  -vf)
    VF=${VF:+$VF,}$2
    shift ;;
  -w|--width)
    [ -n "$VF" ] && VF+=,
    VF+="scale=${2}:-1"
    shift ;;
  -dn|--denoise)
    [ -n "$VF" ] && VF+=,
    if [[ $2 =~ ^[0-9.:]+$ ]]; then
      IFS=: read -ra dn <<< "$2"
      shift
    fi
    VF+="hqdn3d=${dn[0]-4}:${dn[1]-3}:${dn[2]-6}:${dn[3]-4.5}" ;;
  -di|--deinterlace)
    [ -n "$VF" ] && VF+=,
    VF+=yadif ;;
  -ds|--deshake)
    [ -n "$VF" ] && VF+=,
    VF+=deshake ;;
  -cw)
    [ -n "$VF" ] && VF+=,
    VF+=transpose=1 ;;
  -ccw)
    [ -n "$VF" ] && VF+=,
    VF+=transpose=2 ;;
  -eq)
    [[ -n $VF ]] && VF+=,
    local eq
    IFS=: read -ra eq <<< "$2"
    VF+=eq=contrast=${eq[0]-1}:brightness=${eq[1]-0}:gamma=${eq[2]-1}
    shift ;;
  --ultrafast|--superfast|--veryfast|--faster|--fast|--medium|--slow|--slower|--veryslow)
    preset=${1##--} ;;
  --film|--animation|--grain|--stillimage|--fastdecode|--zerolatency)
    tune=${1##--} ;;
  -2)
    p2only="-pass 2" ;;
  -cr|--crop)
    [[ -n $VF ]] && VF+=,
    VF+=crop=$2
    shift ;;
  -sc)
    scopy="-c:s copy" ;;
  -t|--threads)
    threads=$2
    shift ;;
  --log)
    [ "$2" == "quiet" ] && local NOLOG=1
    LOG="-v $2"
    shift ;;
  -r)
    VF="${VF:+$VF,}fps=$2"
    shift ;;
  -alow)
    audio="-c:a libfdk_aac -ar 22050 -profile:a aac_he -vbr 1 -ac 1" ;;
  -ahigh)
    audio="-c:a libfdk_aac -ar 44100 -vbr 3" ;;
  -an)
    audio="-an" ;;
  *)
    if [ -f "$1" ]; then
      break
    else
      misc+=("$1")
    fi ;;
  esac
  shift
  done

  local passlogfile="${TMPDIR:+$TMPDIR/}ffmpeg2pass-`basename $1 .${1##*.}`"

  local ARGS="\
    $FROM -i \"$1\" $DUR \
    -y -hide_banner \
    -c:v libx264 $BV -preset:v $preset ${tune+-tune $tune} \
    ${threads:+-x264-params threads=$threads} \
    ${VF:+-vf $VF} \
    $audio \
    ${AF:+-af $AF} \
    $scopy \
    -passlogfile $passlogfile \
    $LOG \
    ${misc:+\"${misc[@]}\"} \
  "
  # Use custom streams:
  # -map 0:0 -map 0:2 -ac 2 \

  local out=${2:-${1%.*}-out.${1##*.}}
  [ -z "$NOLOG" ] && _log "< $1"

  # WARN: When using option -an, you may eventually get a segfault # or a broken
  # file. If so, remove option -an and replace by -vsync cfr to the first pass.
  local pass1="ffmpeg $ARGS -pass 1 -an -f null /dev/null"
  local pass2="ffmpeg $ARGS $p2only \"$out\""

  [ ! ${p2only+y}  ] && eval "$pass1" || :
  (( ! $?         )) && eval "$pass2"

  [ -z "$NOLOG" ] && (( ! $? )) && _log "> $out"
}

webm() {
  if (( ! $# )); then
    cat <<EOF
Make webm out of video
$(_usage) [options] <input> [output.webm]
$(_param "-f|--from" "00:00:00.000" "    Starting time for video encoding")
$(_param "-d|--duration" "00:00:00.000" "Total duration time for video encoding")

$(_param "-b|--bitrate" "000k" "Video encoding bitrate")
$(_param "-w|--width" "000" "   Output video width (preserves aspect ratio)")

$(_param -2 "Perform only 2nd pass encoding")
$(_param --mono "Mono audio")

$(_param -eq "contrast:brightness:gamma" "\nApply eq flter
contrast   = 1 [-2.0 ..  2.0]
brightness = 0 [-1.0 ..  1.0]
gamma      = 1 [ 0.1 ..  10 ]")
$(_param "-cr|--crop" "width:height:x:y" "\nApply crop flter
x,y - crop start position from top left corner")
$(_param "-dn|--denoise" "Apply denoise filter")
$(_param -vf "'filters'" "Additional video filters to apply")
EOF
    return 1
  fi

#    echo "$(_usage) [-w width] [-b bitrate] [-r frame-rate] \
#[-f from] [-d duration] [--stereo] [-vf video-filters] \
#[--preview image] <file>"

  local FROM
  local DUR
  local BV
  local R=24
  local AC=2
  local pr_i
  local pr_vf
  local pass2=0
  local IN
  local OUT

  while [[ $# > 1 ]]; do
  case "$1" in
  -f|--from)
    FROM="$2"
    shift ;;
  -d|--duration)
    DUR="-t $2"
    shift ;;
  -b|--bitrate)
    BV="-b:v $2"
    shift ;;
  -vf)
    [[ -n $VF ]] && VF+=,
    VF+=$2
    shift ;;
  -dn|--denoise)
    [ -n "$VF" ] && VF+=,
    if [[ $2 =~ ^[0-9.:]+$ ]]; then
      IFS=: read -ra dn <<< "$2"
      shift
    fi
    VF+="hqdn3d=${dn[0]-4}:${dn[1]-3}:${dn[2]-6}:${dn[3]-4.5}" ;;
  -w|--width)
    [[ -n $VF ]] && VF+=,
    VF+="scale=${2}:-1"
    shift ;;
  -r|--rate)
    R=$2
    shift ;;
  --mono)
    AC=1 ;;
  -pr|--preview)
    pr_i="-i $2"
    pr_vf="[0:v][1:v]overlay=0:0:enable="
    shift ;;
  -2)
    pass2=1 ;;
  *)
    (( $# > 2 )) && _log "Unknown argument '$1'!" && return 1
    break ;;
  esac
  shift
  done

  [[ $# = 2 && $2 != *.webm ]] && _log "Wrong output file '$2' must be *.webm!" && return 1
  IN="$1"
  OUT="$2"

  if [[ -n $VF$pr_vf ]]; then
    if [[ -n $pr_vf ]]; then
      pr_vf+="'"
      [[ -n $FROM ]] && pr_vf+="lte(t,$FROM+0.01)" \
                     || pr_vf+="lte(n,1)"
      pr_vf+="'"
    fi
    [[ -n $VF && -n $pr_vf ]] && VF=,$VF
    VF="$pr_vf$VF"
  fi

  FROM=${FROM:+-ss $FROM}
  ARGS="-y -hide_banner $pr_i \
        -c:v libvpx-vp9 -r $R $BV -crf 4 \
        -tile-columns 3 -threads 12 -row-mt 1 \
        -g 9999 -frame-parallel 0 -pix_fmt +yuv420p -sn \
        -c:a libopus -vbr constrained -b:a 96k -cutoff 12000 -ac $AC"

  (( ! $pass2 )) && ffmpeg -i "$IN" $ARGS ${VF:+-filter_complex $VF} -pass 1 -an -f webm $FROM $DUR /dev/null || :
  (( ! $? ))     && ffmpeg -i "$IN" $ARGS ${VF:+-filter_complex $VF} -pass 2 $FROM $DUR "${OUT:-${IN%.*}-out.webm}"

  (( ! $? )) && echo "Video converted!"
}

gif() {
  if (( ! $# )); then
    cat <<EOF
Convert video to GIF
$(_usage) [options] <input> [output.gif]
$(_param "-f|--from" "    00:00:00.000" "Starting time for video encoding")
$(_param "-d|--duration" "00:00:00.000" "Total duration time for video encoding")

$(_param "-w|--width" "  000 " "Output video width (preserves aspect ratio)")

$(_param -2 "Perform only 2nd pass encoding")
$(_param --diff "Use \"stats_mode=diff\", which favors moving (def. \"full\")")
$(_param --dithering "none|bayer:bayer_scale=N|floyd_steinberg|sierra2|sierra2_4a" "(def. \"floyd_steinberg\")")
$(_param --fps 15 "")
$(_param --log "quiet|panic|fatal|error|warning|info|verbose|debug|trace" "")

$(_param "-di|--deinterlace")
$(_param "-dn|--denoise" "luma_spatial:chroma_spatial:luma_tmp:chroma_tmp" \
"\nApply denoise filter.
Default values:
luma_spatial   = 4
chroma_spatial = 3
luma_tmp       = 6
chroma_tmp     = 4.5")

$(_param -eq "contrast:brightness:gamma" \
"\nApply eq flter.
Default values and possible ranges:
contrast   = 1 [-2.0 ..  2.0]
brightness = 0 [-1.0 ..  1.0]
gamma      = 1 [ 0.1 ..  10 ]")

$(_param "-cr|--crop" "width:height:x:y" \
"\nApply crop flter.
x,y - crop start position from top left corner")

$(_param -vf filters "Additional video filters to apply")
EOF
    return 1
  fi

  local pass2=0
  local smode=full
  local dith=floyd_steinberg
  local fps=5
  local colors=32

  while [[ $# > 1 ]]; do
  case "$1" in
  -f|--from)
    FROM="-ss $2"
    shift ;;
  -d|--duration)
    DUR="-t $2"
    shift ;;
  -vf)
    [ -n "$VF" ] && VF+=,
    VF+=$2
    shift ;;
  -w|--width)
    [ -n "$VF" ] && VF+=,
    VF+="scale=${2}:-1:flags=lanczos"
    shift ;;
  -dn|--denoise)
    [ -n "$VF" ] && VF+=,
    if [[ $2 =~ ^[0-9.:]+$ ]]; then
      IFS=: read -ra dn <<< "$2"
      shift
    fi
    VF+="hqdn3d=${dn[0]-4}:${dn[1]-3}:${dn[2]-6}:${dn[3]-4.5}" ;;
  -eq)
    [[ -n $VF ]] && VF+=,
    local eq
    IFS=: read -ra eq <<< "$2"
    VF+=eq=contrast=${eq[0]-1}:brightness=${eq[1]-0}:gamma=${eq[2]-1}
    shift ;;
  --diff)
    smode=diff ;;
  --dithering)
    dith=$2
    shift ;;
  --fps)
    fps=$2
    shift ;;
  -c|--colors)
    colors=$2
    shift ;;
  -2)
    pass2=1 ;;
  -cr|--crop)
    [[ -n $VF ]] && VF+=,
    VF+=crop=$2
    shift ;;
  --log)
    LOG="-v $2"
    shift ;;
  *)
    (( $# > 2 )) && _log "Unknown argument '$1'!" && return 1
    [[ $# = 2 && $2 != *.gif ]] && _log "Wrong output file '$2' must be *.gif!" && return 1
    break ;;
  esac
  shift
  done

  [ -n "$VF" ] && VF+=,
  VF+="fps=$fps"

  local ARGS="$FROM $DUR -y -hide_banner $LOG"

  local out=${2:-${1%.*}-out.gif}
  local palette="/tmp/palette-${out%.*}.png"
  local VF1="$VF,palettegen=stats_mode=$smode:max_colors=$colors"
  local VF2="$VF [x]; [x][1:v] paletteuse=dither=$dith"

  _log "< $1"

  (( ! $pass2 ))       && ffmpeg $ARGS -i "$1" -vf "$VF1" "$palette"
  (( ! $? || $pass2 )) && ffmpeg $ARGS -i "$1" -i $palette -lavfi "$VF2" "$out"

  (( ! $? )) && _log "> $out"
}

if (( ! $# )); then
  cat <<EOF
Universal media convertor
$(_usage) <ao|audio|concat|covers|cut|gif|videos|vol|photos|film|webm>
EOF
else
  CMD="$1"
  shift
  $CMD "$@"
fi
