#!/bin/sh

# In God We Trust †
#
# A.D. MMXXIV

if [ $# -lt 2 ]; then
	>&2 cat <<EOF
Usage: `basename $0` <SRC_LANG> <TRG_LANG> [VAR]

Translates stdin lines from SRC_LANG to TRG_LANG,
providing VAR (default: 1) number of variants.

Languages are: RU, EN, LV, DE, FR, JP, etc.
EOF
	exit 1
fi

SRC_LANG=$1
TRG_LANG=$2
VAR=${3:-1}

ID=$((`shuf -i1-9999 -n1` * 10000))

while read REPLY; do
	REPLY=`echo "$REPLY" | sed 's/"/\\\"/g'`
	TS=`date +%s`$(printf '%03d' `shuf -i1-999 -n1`)

	curl -s 'https://www2.deepl.com/jsonrpc?method=LMT_handle_jobs' \
		-H 'authority: www2.deepl.com' \
		-H 'accept: */*' \
		-H 'accept-language: en-US,en;q=0.9' \
		-H 'content-type: application/json' \
		-H 'cookie: INGRESSCOOKIE=40113e0dee4b96a841229ea7fdb90a3d|a6d4ac311669391fc997a6a267dc91c0; userCountry=LV; dapUid=7a4606c8-30cc-4cee-b72b-2237f4d79494; LMTBID=v2|f5f5dc8e-102c-4388-a21d-826ec841d51a|8a4939eeb193d02099407b235385c633; dapSid=%7B%22sid%22%3A%22dfab2cbd-5a63-433b-a4bc-c222bb8bd3e2%22%2C%22lastUpdate%22%3A1714244541%7D' \
		-H 'dnt: 1' \
		-H 'origin: https://www.deepl.com' \
		-H 'referer: https://www.deepl.com/' \
		-H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120"' \
		-H 'sec-ch-ua-mobile: ?1' \
		-H 'sec-ch-ua-platform: "Android"' \
		-H 'sec-fetch-dest: empty' \
		-H 'sec-fetch-mode: cors' \
		-H 'sec-fetch-site: same-site' \
		-H 'user-agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36' \
		--data-raw '{"jsonrpc":"2.0","method": "LMT_handle_jobs","params":{"jobs":[{"kind":"default","sentences":[{"text":"'"$REPLY"'","id":1,"prefix":""}],"raw_en_context_before":[],"raw_en_context_after":[],"preferred_num_beams":'$VAR'}],"lang":{"target_lang":"'$TRG_LANG'","preference":{"weight":{},"default":"default"},"source_lang_user_selected":"'$SRC_LANG'"},"priority":-1,"commonJobParams":{"mode":"translate","textType":"plaintext","browserType":1},"timestamp":'$TS'},"id":'$ID'}' \
		--compressed \
	| jq -r '
		if .result then
			.result.translations[].beams[].sentences[].text
			| @text "[32m>\(.)[39m"
		else
			.error.message
			| @text "[31m\"\(.)\"[39m"
		end
	'
	echo

	ID=$(($ID + 1))
done
