#!/bin/sh

TMPDIR="${TMPDIR:-/tmp}"

file=$MY_DOCS/_misc/expenses
temp=`mktemp $TMPDIR/.expenses_XXXX`

read -sp "GPG password: " pass
echo

gpg --batch --passphrase $pass -o $temp --yes -qd $file
if (( $? )); then
  shred -u $temp
  exit 1
fi

gnumeric $temp

if gpg --batch --passphrase $pass -o $file --yes -qc $temp; then
  echo 'Expenses were updated!'
fi

shred -u $temp
