#!/bin/sh

# class=`xprop | grep WM_CLASS | cut -d\" -f4`
# compton -b --invert-color-include "class_g=\"$class\""

PICOM_INVERT=$TMPDIR/.picom-invert

pkill picom
if [ -f $PICOM_INVERT ]; then
  rm $PICOM_INVERT
  picom -b
else
  picom -b --invert-color-include '
    WM_WINDOW_ROLE@:s = "GtkFileChooserDialog" ||
    name *?= "gnumeric"
  '
  touch $PICOM_INVERT
fi
