#!/bin/bash

memo=$MY_DOCS/_misc/memo

check_memo() {
  if [[ ! -f $memo ]]; then
    echo "No memo at $memo"
    exit 1
  fi
}

check_shred() {
  if ! which shred >/dev/null; then
    echo "No 'shred' available!"
    exit 1
  fi
}

join_by() { local IFS="$1"; shift; echo "$*"; }

_copy() {
  termux-clipboard-set 2>/dev/null \
  || xclip -i -selection clipboard 2>/dev/null \
  || pbcopy

  (( ! $? )) && echo "Copied to clipboard!"
}

show() {
  local list="$1"
  local c=`echo "$list" | wc -l`
  if (( $c > 1 )); then
    echo "$list"
  elif [[ -n "$list" ]]; then
    local res=`echo $list | cut -d' ' -f2- | sed s/%/%%/g`
    echo "$res"
    printf "$res" | _copy
  else
    echo "No entries!"
  fi
}

m() {
  check_memo

  if (( ! $# )); then
    local list=(`gpg -qd $memo | cut -d' ' -f1`)
    echo ${list[@]}
  elif (( $# == 1 )); then
    local list="`gpg -qd $memo | grep -i $1`"
    show "$list"
  else
    local q=`join_by \| $*`
    local list="`gpg -qd $memo | grep -iE $q`"
    show "$list"
  fi
}

me() {
  check_memo
  check_shred

  local temp=$(
    cd $TMPDIR
    local f=`mktemp .memo_XXXX`
    echo $TMPDIR/$f
  )

  local pass
  read -sp "GPG password: " pass
  echo

  gpg --batch --passphrase $pass -o $temp --yes -qd $memo
  if (( $? )); then
    shred -u $temp
    return 1
  fi
  vim $temp
  if (( $? )); then
    shred -u $temp
    echo Update cancelled.
    return 1
  fi
  gpg --batch --passphrase $pass -o $memo --yes -qc $temp
  local r=$?
  shred -u $temp
  (( ! $r )) && echo Memo updated!
}

case "$1" in
  --help|-h) echo "Usage: ${0##*/} --edit|-e | --help|-h | keys..." ;;
  --edit|-e) me ;;
  *)         m "$@" ;;
esac
