#!/usr/bin/env python3

import sys, os, json, requests, re

templ_path = os.path.dirname(sys.argv[0]) + "/postman-templates"

if len(sys.argv) == 1:
    print("Add as an argument name of a JSON within '%s':" % templ_path)
    for f in os.listdir(templ_path):
        print(f)
    exit()

file = sys.argv[1]
files = list(filter(lambda f: re.match('^.*' + file + '.*\.json$', f), os.listdir(templ_path)))

l = len(files)
if l == 0:
    print('No file containing "%s" was found.' % (file))
    exit()
elif l > 1:
    print('Several files matched!')
    for f in files:
        print(f)
    exit()

file = files[0]
with open(templ_path + "/" + file, 'r') as f:
    pm_json = json.loads(f.read())

if len(sys.argv) == 2:
    print("Choose 'name' argument wisely...")
    for item in pm_json["item"]:
        print(item["name"])
    exit()

name = sys.argv[2]
filtered = list(filter(lambda i: name in i["name"], pm_json["item"]))

l = len(filtered)
if l == 0:
    print('No request containing "%s" was found.' % (name))
    exit()
elif l > 1:
    print('Several requests contain "%s", which one to execute?' % (name))
    print('[0] ALL')
    for idx, item in enumerate(filtered):
        print(" %d  %s" % (idx + 1, item['name']))
    try:
        ans = int(input('\nAnd the answer is: '))
    except ValueError:
        ans = 0
    if ans < 0 or ans > l:
        print('Ha-ha! Not funny.')
        exit()
    elif ans > 0:
        filtered = [filtered[ans - 1]]

for item in filtered:
    r = item["request"]
    url = r["url"]
    body = r["body"]["raw"]
    headers = dict([ (h["key"], h["value"]) for h in r["header"] ])

    method = r["method"]
    print("\n%s %s" % (method, url))
    if method == "POST":
        result = requests.post(url, headers = headers, data = body)
    elif method == "GET":
        result = requests.get( url, headers = headers, data = body)
    elif method == "PUT":
        result = requests.put( url, headers = headers, data = body)

    print(result.text)
