#!/bin/sh

TMPDIR=${TMPDIR:-/tmp}

CURR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo "Current mode: $CURR"

# CPU

[ $CURR = performance ] && MODE=powersave || MODE=performance
for c in `ls -d /sys/devices/system/cpu/cpu[0-9]*`; do
  sudo sh -c "echo $MODE > $c/cpufreq/scaling_governor" || exit 1
done
echo "CPU's set to $MODE mode."

# Bluetooth

BT_IDX=`rfkill list | grep -i bluetooth | head -1 | cut -d: -f1`
if [ $MODE = performance ]; then
  sudo rfkill unblock $BT_IDX || exit 1
  echo "Bluetooth enabled"
elif bluetoothctl info | grep -q "Connected: yes"; then
  echo
  echo "Unable to disable bluetooth, following devices connected:"
  bluetoothctl info | grep "Name:" | cut -d\  -f2-
else
  sudo rfkill block $BT_IDX || exit 1
  echo "Bluetooth disabled"
fi

# PCI devices

_join() {
  local IFS="$1"
  shift
  echo "$*"
}

if [ $MODE = powersave ]; then
  PCI_DVCS=()
  # Nvidia VGA
  PCI_DVCS+=(10de:1c8c)
  # Nvidia audio
  PCI_DVCS+=(10de:0fb9)
  # ThinkPad ethernet
  PCI_DVCS+=(8086:15bb)
  # TODO 0000:09:00.0 Samsung netbook ethernet

  IFS=$'\r\n' PCI_DVCS=($(lspci -nn | sed -En "s/([^ ]+) [^:]+: (.+) \[(`_join \| ${PCI_DVCS[@]}`)\].*/\1 \2/p"))

  echo
  for d in "${PCI_DVCS[@]}"; do
    IFS=\  d=(echo $d)
    DEV=(/sys/bus/pci/devices/*${d[1]})
    NAME=${d[@]:2}
    sudo sh -c "echo 1 > $DEV/remove" || exit 1
    echo "PCI device removed: $NAME"
  done
else
  sudo sh -c "echo 1 > /sys/bus/pci/rescan" || exit 1
  echo "PCI devices rescanned."
fi

# Powertop

if [[ ! -f $TMPDIR/.powertop-tuned ]]; then
  echo
  sudo powertop --auto-tune \
  && touch $TMPDIR/.powertop-tuned
fi
