#!/bin/sh

g=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
echo "Current mode: $g"

if [[ $g = powersave ]]; then
  for c in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    sudo sh -c "echo performance > $c" || exit 1
    echo "CPU upscaled"
  done
  sudo rfkill unblock 2 || exit 1
  echo "Bluetooth enabled"
else
  for c in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    sudo sh -c "echo powersave > $c" || exit 1
    echo "CPU downscaled"
  done

  # Network?
  if [ -d /sys/bus/pci/devices/0000:09:00.0 ]; then
    sudo sh -c "echo 1 > /sys/bus/pci/devices/0000:09:00.0/remove" || exit 1
  fi

  sudo rfkill block 2 || exit 1
  echo "Bluetooth disabled"

  sudo powertop --auto-tune || exit 1
fi
