#!/bin/sh

# Stats for Zswap & Zram

zs_orig_kb=`awk '/Zswapped:/{print $2}' /proc/meminfo`
zs_orig_mb=$(($zs_orig_kb / 1024))
if (( $zs_orig_mb > 0 )); then
  echo "=== ZSWAP ==="
  zs_used_kb=`awk '/Zswap:/{print $2}' /proc/meminfo`
  zs_used_mb=$(($zs_used_kb / 1024))
  zs_total_mb=`command bc -l <<< "
    x = \
    $(awk '/MemTotal:/{print $2 / 1024}' /proc/meminfo) \
    * $(cat /sys/module/zswap/parameters/max_pool_percent) / 100 \
    + 0.5 # rounding
    scale = 0
    print x/1
  "`
  echo "Orig: ${zs_orig_mb}M"
  echo "Used: ${zs_used_mb}M / ${zs_total_mb}M"
  echo "Comp: $((($zs_orig_kb - $zs_used_kb) * 100 / $zs_orig_kb))%"
else
  echo "--- ZSWAP ---"
fi
echo

zr=(`cat /sys/block/zram0/mm_stat`)
zr_orig=${zr[0]}
zr_orig_mb=$(($zr_orig/1024**2))
if (( $zr_orig_mb > 0 )); then
  zr_used_mb=$((${zr[2]}/1024**2))
  zr_total_mb=$((${zr[3]}/1024**2))
  zr_comp=${zr[1]}

  echo "=== ZRAM ==="
  echo "Orig: ${zr_orig_mb}M"
  echo "Used: ${zr_used_mb}M / ${zr_total_mb}M"
  echo "Comp: $((($zr_orig-$zr_comp)*100/$zr_orig))%"
else
  echo "--- ZRAM ---"
fi
